### ISSUE TITLE
Reference to your code

### ISSUE THREAD

**Issue by MasamMahmood** [anoop4real/FileDownloader#1]
Can I ask question related to File Downloader thing?

**Comment by anoop4real** [comment]
Sure, its been quite some time since I have looked into this code...but feel free to ask

**Comment by MasamMahmood** [comment]
First of all Thank you. Actually I used your code specially the download Classes `NetworkDataManager & DownloadData` . According to my need I group or club them its fine for data purpose.
But related to progress bar I am not able to manage `progressBar` club or group them I struggling hard since last two weeks. 
How will I do that ? 
Secondly sometimes `Unexpectedly found nil while unwrapping an Optional value` on ` NetworkDataManager.swift  - line 140`. Its a completion handler. 

Summarized Issues: 
- First is club or group Progress bar (at the moment data is grouped but not progress bar)

- Second NetworkDataManager line 140 issue. 

My reference code link: 
https://github.com/MasamMahmood/downloadManagerTest

**Comment by anoop4real** [comment]
Hi,
I have checked the code.. it worked fine for me...anyways what do you mean by  club or group progress  bar?
For second issue, `getCompletionHandlerForTask`  returns an optional handler, may  be for some reason  the  handler is getting removed from  the dictionary. What  you can do is to use `completionHandler?` instead of `completionHandler! ` , see if things are working
But it is strange why handler becomes nil.

**Comment by MasamMahmood** [comment]
Hi 
Thank you for reply.
Related to first Issue,  I have multiple appointments in `appointment.json` and every appointment is pointed  to `appointmentDetail.json` which is detailed one and it contains multiple pdf files. 
if I summarize it  -> my means every appointment has multiple files. 

According to your code, progress bar shows only the first pdf download and speed up and progress finished.  But I want to do until all files download (based on files) progress bar continues and completes.
At the moment progress bar is so fast because it shows only for one file. ( thats my mean for club or group).

**Comment by anoop4real** [comment]
Hi,
I will try  to  check during the weekend.

**Comment by MasamMahmood** [comment]
Thank you.

**Comment by MasamMahmood** [comment]
have you got any chance ?

**Comment by anoop4real** [comment]
[downloadManagerTest-master 2.zip](https://github.com/anoop4real/FileDownloader/files/4298995/downloadManagerTest-master.2.zip)

Hi,
Try this... dont use it as such, make all the necessary handling like, optional checks, error handling etc.. there are major changes required

1. Data source modified to have dictionary so that each appointment has its own downloaddata list.
2. Cell modified to have array of download data
3. Percentage handling modfied to have number of files and percentage
4. Other minor changes here and there...

Again dont use this as such, I would suggest you to rearchitecture the app, to have a better data structure.

**Comment by MasamMahmood** [comment]
Thank you so much definitely I will modify it accordingly as you mentioned.
